/**
 * 智选车API文档
 * 智选车汽车推荐购买平台API文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginDTO model module.
 * @module model/LoginDTO
 * @version 1.0
 */
class LoginDTO {
    /**
     * Constructs a new <code>LoginDTO</code>.
     * @alias module:model/LoginDTO
     * @param loginIdentity {String} 
     * @param password {String} 
     */
    constructor(loginIdentity, password) { 
        
        LoginDTO.initialize(this, loginIdentity, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, loginIdentity, password) { 
        obj['loginIdentity'] = loginIdentity;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>LoginDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginDTO} obj Optional instance to populate.
     * @return {module:model/LoginDTO} The populated <code>LoginDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginDTO();

            if (data.hasOwnProperty('loginIdentity')) {
                obj['loginIdentity'] = ApiClient.convertToType(data['loginIdentity'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('loginType')) {
                obj['loginType'] = ApiClient.convertToType(data['loginType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoginDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LoginDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LoginDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['loginIdentity'] && !(typeof data['loginIdentity'] === 'string' || data['loginIdentity'] instanceof String)) {
            throw new Error("Expected the field `loginIdentity` to be a primitive type in the JSON string but got " + data['loginIdentity']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['loginType'] && !(typeof data['loginType'] === 'string' || data['loginType'] instanceof String)) {
            throw new Error("Expected the field `loginType` to be a primitive type in the JSON string but got " + data['loginType']);
        }

        return true;
    }


}

LoginDTO.RequiredProperties = ["loginIdentity", "password"];

/**
 * @member {String} loginIdentity
 */
LoginDTO.prototype['loginIdentity'] = undefined;

/**
 * @member {String} password
 */
LoginDTO.prototype['password'] = undefined;

/**
 * @member {String} loginType
 */
LoginDTO.prototype['loginType'] = undefined;






export default LoginDTO;

