/**
 * 智选车API文档
 * 智选车汽车推荐购买平台API文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PreferenceDTO model module.
 * @module model/PreferenceDTO
 * @version 1.0
 */
class PreferenceDTO {
    /**
     * Constructs a new <code>PreferenceDTO</code>.
     * @alias module:model/PreferenceDTO
     */
    constructor() { 
        
        PreferenceDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PreferenceDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PreferenceDTO} obj Optional instance to populate.
     * @return {module:model/PreferenceDTO} The populated <code>PreferenceDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PreferenceDTO();

            if (data.hasOwnProperty('priceMin')) {
                obj['priceMin'] = ApiClient.convertToType(data['priceMin'], 'Number');
            }
            if (data.hasOwnProperty('priceMax')) {
                obj['priceMax'] = ApiClient.convertToType(data['priceMax'], 'Number');
            }
            if (data.hasOwnProperty('preferredBrands')) {
                obj['preferredBrands'] = ApiClient.convertToType(data['preferredBrands'], 'String');
            }
            if (data.hasOwnProperty('preferredCategories')) {
                obj['preferredCategories'] = ApiClient.convertToType(data['preferredCategories'], 'String');
            }
            if (data.hasOwnProperty('otherPreferences')) {
                obj['otherPreferences'] = ApiClient.convertToType(data['otherPreferences'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PreferenceDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PreferenceDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['preferredBrands'] && !(typeof data['preferredBrands'] === 'string' || data['preferredBrands'] instanceof String)) {
            throw new Error("Expected the field `preferredBrands` to be a primitive type in the JSON string but got " + data['preferredBrands']);
        }
        // ensure the json data is a string
        if (data['preferredCategories'] && !(typeof data['preferredCategories'] === 'string' || data['preferredCategories'] instanceof String)) {
            throw new Error("Expected the field `preferredCategories` to be a primitive type in the JSON string but got " + data['preferredCategories']);
        }
        // ensure the json data is a string
        if (data['otherPreferences'] && !(typeof data['otherPreferences'] === 'string' || data['otherPreferences'] instanceof String)) {
            throw new Error("Expected the field `otherPreferences` to be a primitive type in the JSON string but got " + data['otherPreferences']);
        }

        return true;
    }


}



/**
 * @member {Number} priceMin
 */
PreferenceDTO.prototype['priceMin'] = undefined;

/**
 * @member {Number} priceMax
 */
PreferenceDTO.prototype['priceMax'] = undefined;

/**
 * @member {String} preferredBrands
 */
PreferenceDTO.prototype['preferredBrands'] = undefined;

/**
 * @member {String} preferredCategories
 */
PreferenceDTO.prototype['preferredCategories'] = undefined;

/**
 * @member {String} otherPreferences
 */
PreferenceDTO.prototype['otherPreferences'] = undefined;






export default PreferenceDTO;

