/**
 * 智选车API文档
 * 智选车汽车推荐购买平台API文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('addFavorite', function() {
      it('should call addFavorite successfully', function(done) {
        //uncomment below and update the code to test addFavorite
        //instance.addFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('auditCar', function() {
      it('should call auditCar successfully', function(done) {
        //uncomment below and update the code to test auditCar
        //instance.auditCar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('auditDealer', function() {
      it('should call auditDealer successfully', function(done) {
        //uncomment below and update the code to test auditDealer
        //instance.auditDealer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchDeleteMessages', function() {
      it('should call batchDeleteMessages successfully', function(done) {
        //uncomment below and update the code to test batchDeleteMessages
        //instance.batchDeleteMessages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchMarkRead', function() {
      it('should call batchMarkRead successfully', function(done) {
        //uncomment below and update the code to test batchMarkRead
        //instance.batchMarkRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cancelAppointment', function() {
      it('should call cancelAppointment successfully', function(done) {
        //uncomment below and update the code to test cancelAppointment
        //instance.cancelAppointment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('changeCarStatus', function() {
      it('should call changeCarStatus successfully', function(done) {
        //uncomment below and update the code to test changeCarStatus
        //instance.changeCarStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('checkAppointmentTime', function() {
      it('should call checkAppointmentTime successfully', function(done) {
        //uncomment below and update the code to test checkAppointmentTime
        //instance.checkAppointmentTime(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('checkIsFavorite', function() {
      it('should call checkIsFavorite successfully', function(done) {
        //uncomment below and update the code to test checkIsFavorite
        //instance.checkIsFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clearBrowseHistory', function() {
      it('should call clearBrowseHistory successfully', function(done) {
        //uncomment below and update the code to test clearBrowseHistory
        //instance.clearBrowseHistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clearSearchHistory', function() {
      it('should call clearSearchHistory successfully', function(done) {
        //uncomment below and update the code to test clearSearchHistory
        //instance.clearSearchHistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createAppointment', function() {
      it('should call createAppointment successfully', function(done) {
        //uncomment below and update the code to test createAppointment
        //instance.createAppointment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createCar', function() {
      it('should call createCar successfully', function(done) {
        //uncomment below and update the code to test createCar
        //instance.createCar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBrowseRecord', function() {
      it('should call deleteBrowseRecord successfully', function(done) {
        //uncomment below and update the code to test deleteBrowseRecord
        //instance.deleteBrowseRecord(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCar', function() {
      it('should call deleteCar successfully', function(done) {
        //uncomment below and update the code to test deleteCar
        //instance.deleteCar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCar1', function() {
      it('should call deleteCar1 successfully', function(done) {
        //uncomment below and update the code to test deleteCar1
        //instance.deleteCar1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCarDetail', function() {
      it('should call deleteCarDetail successfully', function(done) {
        //uncomment below and update the code to test deleteCarDetail
        //instance.deleteCarDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCarImage', function() {
      it('should call deleteCarImage successfully', function(done) {
        //uncomment below and update the code to test deleteCarImage
        //instance.deleteCarImage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDealer', function() {
      it('should call deleteDealer successfully', function(done) {
        //uncomment below and update the code to test deleteDealer
        //instance.deleteDealer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMessage', function() {
      it('should call deleteMessage successfully', function(done) {
        //uncomment below and update the code to test deleteMessage
        //instance.deleteMessage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSearchRecord', function() {
      it('should call deleteSearchRecord successfully', function(done) {
        //uncomment below and update the code to test deleteSearchRecord
        //instance.deleteSearchRecord(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUser', function() {
      it('should call deleteUser successfully', function(done) {
        //uncomment below and update the code to test deleteUser
        //instance.deleteUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filterCars', function() {
      it('should call filterCars successfully', function(done) {
        //uncomment below and update the code to test filterCars
        //instance.filterCars(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBehaviorRecommendations', function() {
      it('should call getBehaviorRecommendations successfully', function(done) {
        //uncomment below and update the code to test getBehaviorRecommendations
        //instance.getBehaviorRecommendations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBrands', function() {
      it('should call getBrands successfully', function(done) {
        //uncomment below and update the code to test getBrands
        //instance.getBrands(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBrowseHistory', function() {
      it('should call getBrowseHistory successfully', function(done) {
        //uncomment below and update the code to test getBrowseHistory
        //instance.getBrowseHistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarAppointments', function() {
      it('should call getCarAppointments successfully', function(done) {
        //uncomment below and update the code to test getCarAppointments
        //instance.getCarAppointments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarAuditList', function() {
      it('should call getCarAuditList successfully', function(done) {
        //uncomment below and update the code to test getCarAuditList
        //instance.getCarAuditList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarDetail', function() {
      it('should call getCarDetail successfully', function(done) {
        //uncomment below and update the code to test getCarDetail
        //instance.getCarDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarDetail1', function() {
      it('should call getCarDetail1 successfully', function(done) {
        //uncomment below and update the code to test getCarDetail1
        //instance.getCarDetail1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarDetail2', function() {
      it('should call getCarDetail2 successfully', function(done) {
        //uncomment below and update the code to test getCarDetail2
        //instance.getCarDetail2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarFavoriteCount', function() {
      it('should call getCarFavoriteCount successfully', function(done) {
        //uncomment below and update the code to test getCarFavoriteCount
        //instance.getCarFavoriteCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarImages', function() {
      it('should call getCarImages successfully', function(done) {
        //uncomment below and update the code to test getCarImages
        //instance.getCarImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCars', function() {
      it('should call getCars successfully', function(done) {
        //uncomment below and update the code to test getCars
        //instance.getCars(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarsByBrand', function() {
      it('should call getCarsByBrand successfully', function(done) {
        //uncomment below and update the code to test getCarsByBrand
        //instance.getCarsByBrand(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarsByCategory', function() {
      it('should call getCarsByCategory successfully', function(done) {
        //uncomment below and update the code to test getCarsByCategory
        //instance.getCarsByCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCarsByPriceRange', function() {
      it('should call getCarsByPriceRange successfully', function(done) {
        //uncomment below and update the code to test getCarsByPriceRange
        //instance.getCarsByPriceRange(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCategories', function() {
      it('should call getCategories successfully', function(done) {
        //uncomment below and update the code to test getCategories
        //instance.getCategories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChatMessages', function() {
      it('should call getChatMessages successfully', function(done) {
        //uncomment below and update the code to test getChatMessages
        //instance.getChatMessages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContentStatistics', function() {
      it('should call getContentStatistics successfully', function(done) {
        //uncomment below and update the code to test getContentStatistics
        //instance.getContentStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDealerAppointments', function() {
      it('should call getDealerAppointments successfully', function(done) {
        //uncomment below and update the code to test getDealerAppointments
        //instance.getDealerAppointments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDealerDetail', function() {
      it('should call getDealerDetail successfully', function(done) {
        //uncomment below and update the code to test getDealerDetail
        //instance.getDealerDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDealerList', function() {
      it('should call getDealerList successfully', function(done) {
        //uncomment below and update the code to test getDealerList
        //instance.getDealerList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoriteCount', function() {
      it('should call getFavoriteCount successfully', function(done) {
        //uncomment below and update the code to test getFavoriteCount
        //instance.getFavoriteCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoriteList', function() {
      it('should call getFavoriteList successfully', function(done) {
        //uncomment below and update the code to test getFavoriteList
        //instance.getFavoriteList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHomeRecommendations', function() {
      it('should call getHomeRecommendations successfully', function(done) {
        //uncomment below and update the code to test getHomeRecommendations
        //instance.getHomeRecommendations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHotRecommendations', function() {
      it('should call getHotRecommendations successfully', function(done) {
        //uncomment below and update the code to test getHotRecommendations
        //instance.getHotRecommendations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getInteractionMessages', function() {
      it('should call getInteractionMessages successfully', function(done) {
        //uncomment below and update the code to test getInteractionMessages
        //instance.getInteractionMessages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewCarRecommendations', function() {
      it('should call getNewCarRecommendations successfully', function(done) {
        //uncomment below and update the code to test getNewCarRecommendations
        //instance.getNewCarRecommendations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPendingCount', function() {
      it('should call getPendingCount successfully', function(done) {
        //uncomment below and update the code to test getPendingCount
        //instance.getPendingCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPendingDealers', function() {
      it('should call getPendingDealers successfully', function(done) {
        //uncomment below and update the code to test getPendingDealers
        //instance.getPendingDealers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPreferenceRecommendations', function() {
      it('should call getPreferenceRecommendations successfully', function(done) {
        //uncomment below and update the code to test getPreferenceRecommendations
        //instance.getPreferenceRecommendations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSearchHistory', function() {
      it('should call getSearchHistory successfully', function(done) {
        //uncomment below and update the code to test getSearchHistory
        //instance.getSearchHistory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSystemMessages', function() {
      it('should call getSystemMessages successfully', function(done) {
        //uncomment below and update the code to test getSystemMessages
        //instance.getSystemMessages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSystemStatistics', function() {
      it('should call getSystemStatistics successfully', function(done) {
        //uncomment below and update the code to test getSystemStatistics
        //instance.getSystemStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUnreadCount', function() {
      it('should call getUnreadCount successfully', function(done) {
        //uncomment below and update the code to test getUnreadCount
        //instance.getUnreadCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUpcomingAppointments', function() {
      it('should call getUpcomingAppointments successfully', function(done) {
        //uncomment below and update the code to test getUpcomingAppointments
        //instance.getUpcomingAppointments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAppointments', function() {
      it('should call getUserAppointments successfully', function(done) {
        //uncomment below and update the code to test getUserAppointments
        //instance.getUserAppointments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserDetail', function() {
      it('should call getUserDetail successfully', function(done) {
        //uncomment below and update the code to test getUserDetail
        //instance.getUserDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserInterests', function() {
      it('should call getUserInterests successfully', function(done) {
        //uncomment below and update the code to test getUserInterests
        //instance.getUserInterests(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserList', function() {
      it('should call getUserList successfully', function(done) {
        //uncomment below and update the code to test getUserList
        //instance.getUserList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserPreference', function() {
      it('should call getUserPreference successfully', function(done) {
        //uncomment below and update the code to test getUserPreference
        //instance.getUserPreference(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserProfile', function() {
      it('should call getUserProfile successfully', function(done) {
        //uncomment below and update the code to test getUserProfile
        //instance.getUserProfile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserStatistics', function() {
      it('should call getUserStatistics successfully', function(done) {
        //uncomment below and update the code to test getUserStatistics
        //instance.getUserStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('login', function() {
      it('should call login successfully', function(done) {
        //uncomment below and update the code to test login
        //instance.login(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('logout', function() {
      it('should call logout successfully', function(done) {
        //uncomment below and update the code to test logout
        //instance.logout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('markMessageRead', function() {
      it('should call markMessageRead successfully', function(done) {
        //uncomment below and update the code to test markMessageRead
        //instance.markMessageRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recordBrowse', function() {
      it('should call recordBrowse successfully', function(done) {
        //uncomment below and update the code to test recordBrowse
        //instance.recordBrowse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recordSearch', function() {
      it('should call recordSearch successfully', function(done) {
        //uncomment below and update the code to test recordSearch
        //instance.recordSearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('register', function() {
      it('should call register successfully', function(done) {
        //uncomment below and update the code to test register
        //instance.register(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeFavorite', function() {
      it('should call removeFavorite successfully', function(done) {
        //uncomment below and update the code to test removeFavorite
        //instance.removeFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resetUserPassword', function() {
      it('should call resetUserPassword successfully', function(done) {
        //uncomment below and update the code to test resetUserPassword
        //instance.resetUserPassword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('saveCarDetail', function() {
      it('should call saveCarDetail successfully', function(done) {
        //uncomment below and update the code to test saveCarDetail
        //instance.saveCarDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchCars', function() {
      it('should call searchCars successfully', function(done) {
        //uncomment below and update the code to test searchCars
        //instance.searchCars(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendMessage', function() {
      it('should call sendMessage successfully', function(done) {
        //uncomment below and update the code to test sendMessage
        //instance.sendMessage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submitDealerInfo', function() {
      it('should call submitDealerInfo successfully', function(done) {
        //uncomment below and update the code to test submitDealerInfo
        //instance.submitDealerInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submitDealerReview', function() {
      it('should call submitDealerReview successfully', function(done) {
        //uncomment below and update the code to test submitDealerReview
        //instance.submitDealerReview(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCar', function() {
      it('should call updateCar successfully', function(done) {
        //uncomment below and update the code to test updateCar
        //instance.updateCar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCarDetail', function() {
      it('should call updateCarDetail successfully', function(done) {
        //uncomment below and update the code to test updateCarDetail
        //instance.updateCarDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePassword', function() {
      it('should call updatePassword successfully', function(done) {
        //uncomment below and update the code to test updatePassword
        //instance.updatePassword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateStatusByDealer', function() {
      it('should call updateStatusByDealer successfully', function(done) {
        //uncomment below and update the code to test updateStatusByDealer
        //instance.updateStatusByDealer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserPreference', function() {
      it('should call updateUserPreference successfully', function(done) {
        //uncomment below and update the code to test updateUserPreference
        //instance.updateUserPreference(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserProfile', function() {
      it('should call updateUserProfile successfully', function(done) {
        //uncomment below and update the code to test updateUserProfile
        //instance.updateUserProfile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserStatus', function() {
      it('should call updateUserStatus successfully', function(done) {
        //uncomment below and update the code to test updateUserStatus
        //instance.updateUserStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadAvatar', function() {
      it('should call uploadAvatar successfully', function(done) {
        //uncomment below and update the code to test uploadAvatar
        //instance.uploadAvatar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadCarImage', function() {
      it('should call uploadCarImage successfully', function(done) {
        //uncomment below and update the code to test uploadCarImage
        //instance.uploadCarImage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
