/**
 * 智选车API文档
 * 智选车汽车推荐购买平台API文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.CarDetailDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CarDetailDTO', function() {
    it('should create an instance of CarDetailDTO', function() {
      // uncomment below and update the code to test CarDetailDTO
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be.a(Api.CarDetailDTO);
    });

    it('should have the property detailId (base name: "detailId")', function() {
      // uncomment below and update the code to test the property detailId
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property carId (base name: "carId")', function() {
      // uncomment below and update the code to test the property carId
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property engine (base name: "engine")', function() {
      // uncomment below and update the code to test the property engine
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property transmission (base name: "transmission")', function() {
      // uncomment below and update the code to test the property transmission
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property fuelType (base name: "fuelType")', function() {
      // uncomment below and update the code to test the property fuelType
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property fuelConsumption (base name: "fuelConsumption")', function() {
      // uncomment below and update the code to test the property fuelConsumption
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property seats (base name: "seats")', function() {
      // uncomment below and update the code to test the property seats
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property bodySize (base name: "bodySize")', function() {
      // uncomment below and update the code to test the property bodySize
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property wheelbase (base name: "wheelbase")', function() {
      // uncomment below and update the code to test the property wheelbase
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property features (base name: "features")', function() {
      // uncomment below and update the code to test the property features
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

    it('should have the property warranty (base name: "warranty")', function() {
      // uncomment below and update the code to test the property warranty
      //var instance = new Api.CarDetailDTO();
      //expect(instance).to.be();
    });

  });

}));
