/**
 * 智选车API文档
 * 智选车汽车推荐购买平台API文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.LoginDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoginDTO', function() {
    it('should create an instance of LoginDTO', function() {
      // uncomment below and update the code to test LoginDTO
      //var instance = new Api.LoginDTO();
      //expect(instance).to.be.a(Api.LoginDTO);
    });

    it('should have the property loginIdentity (base name: "loginIdentity")', function() {
      // uncomment below and update the code to test the property loginIdentity
      //var instance = new Api.LoginDTO();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new Api.LoginDTO();
      //expect(instance).to.be();
    });

    it('should have the property loginType (base name: "loginType")', function() {
      // uncomment below and update the code to test the property loginType
      //var instance = new Api.LoginDTO();
      //expect(instance).to.be();
    });

  });

}));
