/**
 * 智选车API文档
 * 智选车汽车推荐购买平台API文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.UserPreference();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserPreference', function() {
    it('should create an instance of UserPreference', function() {
      // uncomment below and update the code to test UserPreference
      //var instance = new Api.UserPreference();
      //expect(instance).to.be.a(Api.UserPreference);
    });

    it('should have the property preferenceId (base name: "preferenceId")', function() {
      // uncomment below and update the code to test the property preferenceId
      //var instance = new Api.UserPreference();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new Api.UserPreference();
      //expect(instance).to.be();
    });

    it('should have the property priceMin (base name: "priceMin")', function() {
      // uncomment below and update the code to test the property priceMin
      //var instance = new Api.UserPreference();
      //expect(instance).to.be();
    });

    it('should have the property priceMax (base name: "priceMax")', function() {
      // uncomment below and update the code to test the property priceMax
      //var instance = new Api.UserPreference();
      //expect(instance).to.be();
    });

    it('should have the property preferredBrands (base name: "preferredBrands")', function() {
      // uncomment below and update the code to test the property preferredBrands
      //var instance = new Api.UserPreference();
      //expect(instance).to.be();
    });

    it('should have the property preferredCategories (base name: "preferredCategories")', function() {
      // uncomment below and update the code to test the property preferredCategories
      //var instance = new Api.UserPreference();
      //expect(instance).to.be();
    });

    it('should have the property otherPreferences (base name: "otherPreferences")', function() {
      // uncomment below and update the code to test the property otherPreferences
      //var instance = new Api.UserPreference();
      //expect(instance).to.be();
    });

    it('should have the property updateTime (base name: "updateTime")', function() {
      // uncomment below and update the code to test the property updateTime
      //var instance = new Api.UserPreference();
      //expect(instance).to.be();
    });

  });

}));
